Добавляет разметку
htmlacademy-htmlcss/1777645-gllacy-35 pull request #3
Opened 2022-09-25 20:02 UTC by FeHixX

2022-09-26 01:25 UTC, Dima-Dim requested changes

2022-09-26 01:25 UTC, Dima-Dim commented on catalog.html
> +          <img class="page-header-logo" src="#" width="" height="" alt="Логотип Глейси.">
Логотип обычно не является частью навигации.

2022-09-26 01:25 UTC, Dima-Dim commented on catalog.html
> +            <p class="visually-hidden add-cart">Добавить в корзину</p>
По макету это очень похоже на интерактивный элемент, а `p` это не интерактивный элемент.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +            <button class="button button-main add-cart" type="button">Заказать</button>
Не нужно сходу добавлять 3 класса. Достаточно даже 1-го, остальное добавишь при стилизации, если потребуются.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +            <img class="slider-image slider-image-current" src="#" width="306" height="507" alt="Мороженое с клубничным джемом.">
Это не сами по себе изображения, это части слайдов и по разметке они должны быть рядом с остальным их содержимым.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +            <p class="visually-hidden add-cart">Добавить в корзину</p>
Тоже интерактивные элементы.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +            <p class="advantages-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
`p` может оказаться лишним тегом.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +      <article class="news">
Так себе `article` - состоящий из 2-х заголовком и одного предложения описания.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +      <article class="newsletter">
Тоже очень странный `article`.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +            <p class="feedback-address-text">наб. реки Карповки, 5 лит П, Санкт-Петербург</p>
Возможно и тут `p` будет лишним.

2022-09-26 01:25 UTC, Dima-Dim commented on index.html
> +          <address class="feedback-address">
Не нужно в `address` оборачиваь отдельные строки и делать много этих тегов на странице. Хорошо, когда на странице один цельный контейнер с полноценными данными.

2022-09-27 07:16 UTC, FeHixX commented on index.html
> +            <img class="slider-image slider-image-current" src="#" width="306" height="507" alt="Мороженое с клубничным джемом.">
исправил

2022-09-27 07:20 UTC, FeHixX commented on index.html
> +            <p class="visually-hidden add-cart">Добавить в корзину</p>
исправил

2022-09-27 07:25 UTC, FeHixX commented on catalog.html
> +            <p class="visually-hidden add-cart">Добавить в корзину</p>
++

2022-09-27 07:30 UTC, FeHixX commented on catalog.html
> +          <img class="page-header-logo" src="#" width="" height="" alt="Логотип Глейси.">
++, класс по слыслу подходит?

2022-09-27 07:35 UTC, FeHixX commented on index.html
> +            <p class="advantages-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
правильно понял?

2022-09-27 07:37 UTC, FeHixX commented on index.html
> +            <button class="button button-main add-cart" type="button">Заказать</button>
add-card не нужен тк сейчас нет JS, верно?

2022-09-27 07:41 UTC, FeHixX commented on index.html
> +      <article class="news">
можем мы такое разметить как дополнительное содержание?

2022-09-27 07:44 UTC, FeHixX commented on index.html
> +          <address class="feedback-address">
их лучше оборачивать когда они идут попорядку?
(телефон-адресс-email и тд)

2022-09-27 07:47 UTC, FeHixX commented on index.html
> +            <p class="popular-price">320 ₽/кг</p>
Нужно ли обозначать цену тегом <b> для семантики, эли не обязательно?

2022-09-27 07:49 UTC, FeHixX commented on index.html
> +            <a class="navigation-link" href="tel:+78005558628">+7 800 555-86-28</a>
Номер телефона может быть как часть навигации, или подразумевается
что по номеру мы можем быстро связаться с магазином по возникшему вопросу?

2022-09-27 07:51 UTC, FeHixX commented on index.html
> +      <article class="newsletter">
++

2022-09-27 07:52 UTC, FeHixX commented on index.html
> +            <p class="feedback-address-text">наб. реки Карповки, 5 лит П, Санкт-Петербург</p>
мы можем адресс указать семантически тегом < b >, верно?

2022-09-28 01:12 UTC, Dima-Dim commented on catalog.html
> +          <img class="page-header-logo" src="#" width="" height="" alt="Логотип Глейси.">
Класс у тега img может быть и просто logo и header-logo, если логотипов на одной странице несколько и они совсем разные. Нужно ли добавлять ко всему этому page? Кажется не обязательно.

2022-09-28 01:13 UTC, Dima-Dim commented on index.html
> +            <button class="button button-main add-cart" type="button">Заказать</button>
add-card не нужен потому что сейчас он вообще никак не используется :) и будет ли - неизвестно.

2022-09-28 01:13 UTC, Dima-Dim commented on index.html
> +            <p class="advantages-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
лишним - значит его можно убрать и вместо него ничего не добавлять :)

2022-09-28 01:14 UTC, Dima-Dim commented on index.html
> +      <article class="news">
Можно и article оставить, а можно просто сделать div, в данном случае.

2022-09-28 01:14 UTC, Dima-Dim commented on index.html
> +            <p class="feedback-address-text">наб. реки Карповки, 5 лит П, Санкт-Петербург</p>
Опять же, можно просто убрать тег p.

2022-09-28 01:19 UTC, Dima-Dim commented on index.html
> +          <address class="feedback-address">
Не нужно использовать тег address как теги div p или li, оборачивая в него много кусочков из разных частей страницы. Открыл тег address, разместил в нём весь адрес, закрыл тег address. Не получается разместить в него весь адрес, размести основную его часть.

2022-09-28 01:19 UTC, Dima-Dim commented on index.html
> +            <p class="popular-price">320 ₽/кг</p>
Не обязательно.

2022-09-28 01:20 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="tel:+78005558628">+7 800 555-86-28</a>
Телефон не является частью внутренний навигации, это внешняя ссылка.

2022-09-28 01:22 UTC, merged

2022-09-28 10:55 UTC, FeHixX commented on index.html
> +          <address class="feedback-address">
Можно address обернуть все вместо div?

2022-09-28 11:03 UTC, FeHixX commented on index.html
> +      <article class="news">
А если так?
< section >
  < aside >< /aside >
  < aside >< /aside >
< /section >

2022-09-28 11:19 UTC, FeHixX commented on index.html
> +            <p class="advantages-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
Можешь пояснить, просто если убрать тег тогда текст останется просто в контейнере?

2022-09-28 11:26 UTC, FeHixX commented on index.html
> +            <p class="feedback-address-text">наб. реки Карповки, 5 лит П, Санкт-Петербург</p>
И тут не понимаю, поясни

2022-09-29 06:29 UTC, Dima-Dim commented on index.html
> +          <address class="feedback-address">
Не понял вопроса. Напиши в комментрии как хочешь сделать, непосредственно фрагмент кода.

2022-09-29 06:30 UTC, Dima-Dim commented on index.html
> +            <p class="feedback-address-text">наб. реки Карповки, 5 лит П, Санкт-Петербург</p>
```
<address class="feedback-address">
  наб. реки Карповки, 5 лит П, Санкт-Петербург
</address>
```

2022-09-29 06:31 UTC, Dima-Dim commented on index.html
> +      <article class="news">
https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-06

2022-09-29 06:32 UTC, Dima-Dim commented on index.html
> +            <p class="advantages-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
Да :) убрать линий тег.